ability_type: Triggered
distance: Self
effects:
    - effect: You gain [temporary Stamina](scc.v1:mcdm.heroes.v1/rule.health/temporary-stamina) equal to your [Might](scc.v1:mcdm.heroes.v1/rule.character/might) score and can enter your [animal form](scc.v1:mcdm.heroes.v1/complication/animal-form) or hybrid form.
      name: Effect
    - cost: Spend 1 Ferocity
      effect: If you are not [dying](scc.v1:mcdm.heroes.v1/rule.health/dying), you can spend a [Recovery](scc.v1:mcdm.heroes.v1/rule.health/recoveries).
feature_type: ability
flavor: In your anger, you revert to a more bestial form.
keywords:
    - '-'
metadata:
    ability_type: Triggered
    action_type: Triggered
    class: fury
    content: "\n*In your anger, you revert to a more bestial form.*\n\n| **-**       | **Triggered** |\n|-------------|--------------:|\n| **\U0001F4CF Self** |   **\U0001F3AF Self** |\n\n**Trigger:** You lose [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina) and are not [dying](scc.v1:mcdm.heroes.v1/rule.health/dying).\n\n**Effect:** You gain [temporary Stamina](scc.v1:mcdm.heroes.v1/rule.health/temporary-stamina) equal to your [Might](scc.v1:mcdm.heroes.v1/rule.character/might) score and can enter your [animal form](scc.v1:mcdm.heroes.v1/complication/animal-form) or hybrid form.\n\n**Spend 1 Ferocity:** If you are not [dying](scc.v1:mcdm.heroes.v1/rule.health/dying), you can spend a [Recovery](scc.v1:mcdm.heroes.v1/rule.health/recoveries)."
    distance: Self
    feature_type: ability
    flavor: In your anger, you revert to a more bestial form.
    item_id: furious-change
    item_name: Furious Change
    keywords:
        - '-'
    level: 1
    scc:
        - mcdm.heroes.v1/feature.ability.fury.level-1/furious-change
    subclass: stormwight
    target: Self
    type: feature/ability/fury/level-1
name: Furious Change
target: Self
trigger: You lose [Stamina](scc.v1:mcdm.heroes.v1/rule.health/stamina) and are not [dying](scc.v1:mcdm.heroes.v1/rule.health/dying).
type: feature
usage: Triggered
