ability_type: Triggered
cost: 11 Discipline
distance: Self
effects:
    - effect: You take a [bonus](scc.v1:mcdm.heroes.v1/rule.dice/bonuses-and-penalties) [turn](scc.v1:mcdm.heroes.v1/rule.combat/turn) immediately after the triggering creature. This ability can be used only once per [combat round](scc.v1:mcdm.heroes.v1/rule.combat/combat-round).
      name: Effect
feature_type: ability
flavor: You show shadows what true [speed](scc.v1:mcdm.heroes.v1/rule.character/speed) is.
keywords:
    - Psionic
metadata:
    ability_type: Triggered
    action_type: Free triggered
    class: "null"
    content: "\n*You show shadows what true [speed](scc.v1:mcdm.heroes.v1/rule.character/speed) is.*\n\n| **Psionic** | **Free triggered** |\n|-------------|-------------------:|\n| **\U0001F4CF Self** |        **\U0001F3AF Self** |\n\n**Trigger:** Another creature on the encounter map ends their [turn](scc.v1:mcdm.heroes.v1/rule.combat/turn).\n\n**Effect:** You take a [bonus](scc.v1:mcdm.heroes.v1/rule.dice/bonuses-and-penalties) [turn](scc.v1:mcdm.heroes.v1/rule.combat/turn) immediately after the triggering creature. This ability can be used only once per [combat round](scc.v1:mcdm.heroes.v1/rule.combat/combat-round)."
    distance: Self
    feature_type: ability
    flavor: You show shadows what true [speed](scc.v1:mcdm.heroes.v1/rule.character/speed) is.
    item_id: time-loop
    item_name: Time Loop
    keywords:
        - Psionic
    level: 9
    scc:
        - mcdm.heroes.v1/feature.ability.null.level-9/time-loop
    target: Self
    type: feature/ability/null/level-9
name: Time Loop
target: Self
trigger: Another creature on the encounter map ends their [turn](scc.v1:mcdm.heroes.v1/rule.combat/turn).
type: feature
usage: Free triggered
